#!/usr/bin/env bash
set -euo pipefail

# devoid-usb.sh is devoid.sh stripped of TPM, LUKS2, and YubiKey. 
# generated by ChatGPT from devoid.sh
# Install a normal Debian system directly onto a USB disk from a running Debian
# system.  This is the deliberately boring cousin of devoid:
#
#   * GPT
#   * 2 GiB EFI System Partition
#   * XFS root
#   * mmdebstrap
#   * dracut-generated generic initramfs
#   * unsigned UKIs generated by systemd-ukify
#   * systemd-boot in the removable-media fallback path
#   * NO LUKS, TPM, FIDO2/YubiKey, Secure Boot signing, PK/KEK/db enrollment,
#     or EFI boot-entry/NVRAM manipulation
#
# Usage:
#   sudo ./devoid-usb.sh /dev/sdX
#   sudo ./devoid-usb.sh /dev/disk/by-id/usb-...
#
# Optional:
#   sudo DEBIAN_RELEASE=forky ./devoid-usb.sh /dev/sdX
#
# Default is Debian testing (forky).

DEBIAN_RELEASE="${DEBIAN_RELEASE:-forky}"
TARGET="/mnt/devoid-usb-target"
ESP_SIZE="${ESP_SIZE:-2G}"
SCRIPT_PATH="$(readlink -f "$0")"

cleanup_host() {
    local rc=$?
    set +e
    sync
    if mountpoint -q "${TARGET}" 2>/dev/null; then
        umount -R "${TARGET}" 2>/dev/null || true
    fi
    rmdir "${TARGET}" 2>/dev/null || true
    return "$rc"
}

fatal() {
    echo "devoid-usb: $*" >&2
    exit 1
}

wait_for_path() {
    local path=$1
    local i
    for i in {1..50}; do
        [[ -e "$path" ]] && return 0
        udevadm settle || true
        sleep 0.1
    done
    fatal "Timed out waiting for $path"
}

host_side_code() {
    [[ $EUID -eq 0 ]] || fatal "run me as root"
    [[ $# -ge 1 && -n ${1:-} ]] || fatal "usage: $0 /dev/sdX"

    local requested_disk=$1

    apt-get update
    apt-get install -y --no-install-recommends \
        dialog gdisk uuid-runtime parted dosfstools xfsprogs \
        mmdebstrap systemd-container udev util-linux

    local disk
    disk="$(readlink -f "$requested_disk")"
    [[ -b "$disk" ]] || fatal "$requested_disk is not a block device"
    [[ "$(lsblk -dn -o TYPE "$disk")" == "disk" ]] || fatal "$requested_disk is not a whole disk"

    # Refuse to destroy the disk that contains the currently mounted root FS.
    if lsblk -nrpo MOUNTPOINT "$disk" | grep -qx '/'; then
        fatal "$disk contains the running system's root filesystem"
    fi

    local disk_info
    disk_info="$(lsblk -dn -o NAME,SIZE,MODEL,SERIAL,TRAN "$disk" | sed 's/[[:space:]]\+$//')"

    if ! dialog --keep-tite --title "devoid USB installer" --yesno \
        "THIS WILL ERASE THE ENTIRE DISK:\n\n$disk\n\n$disk_info\n\nInstall Debian ${DEBIAN_RELEASE} here?" \
        15 78; then
        clear
        exit 1
    fi
    clear

    # Automounters love USB media.  Remove any existing child mounts before
    # repartitioning, while refusing above if this was the running root disk.
    while read -r node; do
        [[ "$node" == "$disk" ]] && continue
        umount "$node" 2>/dev/null || true
    done < <(lsblk -lnpo NAME "$disk")

    wipefs -a "$disk" || true
    sgdisk --zap-all "$disk"

    local esp_partuuid root_partuuid
    esp_partuuid="$(uuidgen)"
    root_partuuid="$(uuidgen)"

    sgdisk \
        --new=1:2048:+"$ESP_SIZE" \
        --typecode=1:ef00 \
        --change-name=1:"EFI system partition" \
        --partition-guid=1:"$esp_partuuid" \
        "$disk"

    sgdisk \
        --new=2:0:0 \
        --typecode=2:8300 \
        --change-name=2:"Root partition" \
        --partition-guid=2:"$root_partuuid" \
        "$disk"

    partprobe "$disk"
    udevadm trigger --subsystem-match=block
    udevadm settle

    local esp rootpart
    esp="/dev/disk/by-partuuid/$esp_partuuid"
    rootpart="/dev/disk/by-partuuid/$root_partuuid"
    wait_for_path "$esp"
    wait_for_path "$rootpart"

    wipefs -a "$esp"
    mkfs.vfat -F32 -n EFI "$esp"

    local rootfs_uuid
    rootfs_uuid="$(uuidgen)"
    wipefs -a "$rootpart"
    mkfs.xfs -f -m uuid="$rootfs_uuid" -L root "$rootpart"

    mkdir -p "$TARGET"
    mount "$rootpart" "$TARGET"
    mkdir -p "$TARGET/boot/efi" "$TARGET/etc" "$TARGET/home"
    mount -o umask=077 "$esp" "$TARGET/boot/efi"

    cat > "$TARGET/etc/fstab" <<FSTAB
UUID=$rootfs_uuid / xfs defaults,noatime 0 1
PARTUUID=$esp_partuuid /boot/efi vfat defaults,umask=077 0 2
FSTAB

    echo "Bootstrapping Debian ${DEBIAN_RELEASE}..."
    unshare -m mmdebstrap \
        --mode=root \
        --variant=apt \
        --components="main contrib non-free non-free-firmware" \
        --skip=check/empty \
        "$DEBIAN_RELEASE" "$TARGET"

    mkdir -p "$TARGET/etc/kernel"
    cat > "$TARGET/etc/kernel/cmdline" <<CMDLINE
quiet splash rw root=UUID=$rootfs_uuid rootfstype=xfs rootflags=rw
CMDLINE

    local hostname
    hostname="$(dialog --keep-tite --stdout --inputbox \
        "Enter hostname:" 8 50 "devoid-usb")"
    clear
    [[ -n "$hostname" ]] || hostname="devoid-usb"
    echo "$hostname" > "$TARGET/etc/hostname"
    cat >> "$TARGET/etc/hosts" <<HOSTS
127.0.1.1 $hostname
HOSTS

    # The target phase deliberately gets no USB token, TPM, efivarfs or raw
    # block-device passthrough.  /boot/efi is already mounted underneath TARGET.
    unshare -m systemd-nspawn \
        --quiet \
        --directory="$TARGET" \
        --bind-ro="$SCRIPT_PATH:/devoid-usb.sh" \
        --timezone=off \
        --console=interactive \
        -- /devoid-usb.sh target

    # Preserve host NetworkManager profiles when present.  Useful for a rescue
    # stick; remove this block if you don't want credentials copied to the USB.
    mkdir -p "$TARGET/etc/NetworkManager/system-connections"
    if compgen -G '/etc/NetworkManager/system-connections/*' >/dev/null; then
        cp -a /etc/NetworkManager/system-connections/. \
            "$TARGET/etc/NetworkManager/system-connections/"
        chmod 700 "$TARGET/etc/NetworkManager/system-connections"
        chmod 600 "$TARGET/etc/NetworkManager/system-connections/"* 2>/dev/null || true
    fi

    sync
    umount -R "$TARGET"

    dialog --keep-tite --title "devoid USB installer" --msgbox \
        "Done.\n\nDebian ${DEBIAN_RELEASE} is installed on:\n$disk\n\nBoot method: systemd-boot + unsigned UKI\nFirmware fallback: EFI/BOOT/BOOTX64.EFI\nNo firmware boot variables were created." \
        14 72
    clear
}

target_side_code() {
    apt-get update

    export DEBIAN_FRONTEND=dialog
    apt-get install -y -o Dpkg::Progress-Fancy=1 \
        systemd-sysv locales tzdata keyboard-configuration adduser

    # Make machine identity persistent before kernel-install chooses its entry
    # token and UKI filenames.
    systemd-machine-id-setup

    apt-get install -y --no-install-recommends -o Dpkg::Progress-Fancy=1 \
        bash curl git zsh sudo openssh-server openssh-client sshfs dialog \
        network-manager network-manager-tui wpasupplicant systemd-resolved \
        usbutils pciutils iputils-ping nano vim less ca-certificates \
        xfsprogs dosfstools

    # An ordinary password replaces devoid's FIDO2/PAM root login path.
    echo
    echo "Set the root password for the USB installation:"
    passwd root

    # UKI pipeline.  BOOT_ROOT is explicit so kernel-install never has to guess
    # where the ESP lives.
    install -d -m 0755 /etc/kernel /etc/dracut.conf.d
    cat > /etc/kernel/install.conf <<'INSTALLCONF'
BOOT_ROOT=/boot/efi
layout=uki
initrd_generator=dracut
uki_generator=ukify
INSTALLCONF

    cat > /etc/kernel/uki.conf <<'UKICONF'
[UKI]
Cmdline=@/etc/kernel/cmdline
UKICONF

    # This USB is expected to migrate between machines, so do not bake a
    # host-specific storage-driver set into the initramfs.
    cat > /etc/dracut.conf.d/devoid-usb.conf <<'DRACUT'
hostonly="no"
add_dracutmodules+=" bash plymouth drm "
filesystems+=" xfs "
DRACUT

    # Debian's dracut postinst hook creates a conventional initramfs path of its
    # own.  devoid owns kernel-install/UKI generation instead.
    if ! dpkg-divert --list /etc/kernel/postinst.d/dracut | grep -q .; then
        dpkg-divert --local --rename --add /etc/kernel/postinst.d/dracut
    fi

    install -d -m 0755 /etc/kernel/postinst.d
    cat > /etc/kernel/postinst.d/90-kernel-install <<'KERNELHOOK'
#!/bin/sh
set -eu
kernel-install add "$1" "/boot/vmlinuz-$1"
KERNELHOOK
    chmod 0755 /etc/kernel/postinst.d/90-kernel-install

    install -d -m 0755 /etc/kernel/postrm.d
    cat > /etc/kernel/postrm.d/90-kernel-install <<'KERNELRM'
#!/bin/sh
set -eu
kernel-install remove "$1"
KERNELRM
    chmod 0755 /etc/kernel/postrm.d/90-kernel-install

    # We intentionally install the EFI binaries/tools rather than Debian's
    # systemd-boot integration package, then invoke bootctl ourselves with
    # --no-variables.  That guarantees the installer does not create/update
    # Boot#### entries in this machine's firmware NVRAM.
    # Install all UKI/boot machinery before the kernel package so the kernel's
    # postinst hook can successfully create the first UKI on its first pass.
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        systemd-boot-efi systemd-boot-tools systemd-ukify dracut \
        plymouth plymouth-themes \
        firmware-linux-free firmware-linux-nonfree firmware-atheros

    plymouth-set-default-theme solar || true

    # Install systemd-boot both in EFI/systemd and in the standard removable
    # media fallback path EFI/BOOT/BOOTX64.EFI, without touching EFI variables.
    bootctl --esp-path=/boot/efi --no-variables --random-seed=no install

    # Kernel last: all kernel-install, dracut, ukify and ESP plumbing now exists.
    DEBIAN_FRONTEND=noninteractive apt-get install -y linux-image-amd64

    install -d -m 0755 /boot/efi/loader
    cat > /boot/efi/loader/loader.conf <<'LOADER'
timeout 3
editor yes
random-seed-mode off
LOADER

    # Avoid the persistent LoaderSystemToken machinery.  The USB should not
    # require or provision host-specific EFI state just to boot.
    systemctl mask systemd-boot-random-seed.service 2>/dev/null || true
    systemctl mask systemd-boot-system-token.service 2>/dev/null || true

    # Keep the fallback bootloader fresh on later apt upgrades without ever
    # asking bootctl to manipulate NVRAM.
    cat > /etc/apt/apt.conf.d/99devoid-systemd-boot <<'APTCFG'
DPkg::Post-Invoke { "if [ -x /usr/bin/bootctl ] && mountpoint -q /boot/efi; then /usr/bin/bootctl --esp-path=/boot/efi --no-variables update >/dev/null 2>&1 || true; fi"; };
APTCFG

    # Regenerate every installed kernel as a UKI now that all config and tools
    # are present.  This also catches any package-order oddities during apt.
    kernel-install add-all

    systemctl enable NetworkManager.service
    systemctl enable systemd-resolved.service
    systemctl enable ssh.service
    ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf

    echo
    echo "UKIs installed:"
    find /boot/efi/EFI/Linux -maxdepth 1 -type f -name '*.efi' -printf '  %f\n' 2>/dev/null || true
    echo
    echo "Fallback bootloader: /boot/efi/EFI/BOOT/BOOTX64.EFI"
}

case "${1:-}" in
    target)
        target_side_code
        ;;
    "")
        fatal "usage: $0 /dev/sdX"
        ;;
    *)
        trap cleanup_host EXIT INT TERM HUP ERR
        host_side_code "$1"
        trap - EXIT INT TERM HUP ERR
        ;;
esac
